title: Evan Simkowitz
description: >- # this means to ignore newlines until "baseurl:"
  Hello World!
domain: "www.simkowitz.dev"
url: "https://www.simkowitz.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  esimkowitz
linkedin_username: esimkowitz
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
